### ISSUE TITLE
SAVE-PACK leaves environment unusable afterwards

### ISSUE THREAD

**Issue by rhalkyard** [jkotlinski/durexforth#302]
`SAVE-PACK` does not undo its 'packing' operation after it has finished saving, leaving only 32 bytes of free dictionary space. To continue working, the user must reset and run from the saved environment or run `$9fff TOP!` to move the wordlist back to where it belongs (which is what `RESTORE-FORTH` does when starting a packed environment).

As a new user, this behavior seems a bit surprising - I can save the environment with `SAVE-FORTH` and then continue working in it, and would intuitively expect `SAVE-PACK` to work the same way.

If this behavior is intentional, it should probably be documented, but if possible, I think it would be more user-friendly for `SAVE-PACK` to leave the system in the state that it found it.

**Comment by burnsauce** [comment]
This behaviour is not intentional, as I hadn't even considered that use case (continuing operation after saving a packed copy).

One problem with this use case is that you CANNOT call `SAVE-PACK` a second time without breaking the `START` vector.  So the use case is essentially a dead-end: even if you could use the system, you couldn't change it and then save any of your changes.

In this light it might be good to force the reboot, and document that `SAVE-PACK` is a terminal step.

**Comment by burnsauce** [comment]
Thinking more about this makes me realize that `restore-forth` does not correctly restore the start vector, leaving it in a corrupt state for a future `save-forth`.  I'll do some testing and submit a patch.
