### ISSUE TITLE
CRT version unusable?

### ISSUE THREAD

**Issue by renekint** [jkotlinski/durexforth#370]
The CRT version is not functioning properly (did not find any clue on how to get it work right yet - please inform if there is a workaround).

PROBLEM: using the CRT version, the stack is always 'ful' (sic). Maybe it's because the CRT version has the stack read-only?

D64 version works correctly.

System used: Ultimate64, vanilla version with CRT on USB stick, loaded at bootup.

**Comment by jkotlinski** [comment]
Hm... I'm running 3.0.0 cartridge image in VICE emulator and that works just fine.
Maybe Ultimate64 doesn't support the "Simons' BASIC" cartridge type that DurexForth is using?

**Comment by renekint** [comment]
Hi Johan.

Somebody else (Bart van Leeuwen) found the solution. He changed the code (of 1_6_2, not 3_0_0 yet) a bit so it "now explicitly enables the top 8k of the cartridge before copying the contents to ram" (his words, all credits to him). 

So I guess it works in VICE but it would be a problem to make it a real CRT with the original code ;-)

Regards,
René

**Comment by jkotlinski** [comment]
Looking forward to a pull request with the fix!

I am surprised to hear that it would be a problem, because original code
works in both VICE and Ultimate 1541, which are both extremely accurate
(generally speaking).

**Comment by renekint** [comment]
Hey I'm not pointing fingers to 'who is wrong' - just pointing out it does not work on U64 as intended. He told me the fix is just a few bytes. So if that fixed version also works in VICE we might have a winner :-) I'll get back once I got it.

**Comment by bvl1999** [comment]
So, the simple solution is to add a single 'sta $de00' to the cartridge code, before it does the rom to ram copy. That will force the cartridge in 16k mode. 

Parallel to that, the crt file indicates it wants to start in 16k mode, not 8k mode, the UII(+) and U64 should imo care about that. 

p.s. also not ponting fingers here, just noting the cartridge code could be improved to be more robust with this small change, and in the meantime also pursuing the UII/U64 side as this might also show up with another cart based on the same (virtual) hardware.

**Comment by bvl1999** [comment]
> Looking forward to a pull request with the fix! I am surprised to hear that it would be a problem, because original code works in both VICE and Ultimate 1541, which are both extremely accurate (generally speaking).

Pull request done. The code itself works fine, but the .crt file didn't.

As also mentioned in my previous comment, I don't want to point fingers, rather, I think the pull request I did adds a 3 byte patch making the .crt more robust, while in the meantime, the UII+/U64 firmware should look at the game/exrom flags in the crt file. Both solve this actual issue, and both would imo be an improvement beyond this specific issue.

**Comment by Whammo** [comment]
#376 
It seems that it's toggling ROM at $a000 in and out by toggling GAME, while EXROM remains pulled to 0 by the cart.
And then there's LORAM and HIRAM in address $01.

LORAM = 1, HIRAM = 1, GAME = 1, EXROM = 1
C64 boot no cart. Writes to $de00 won't affect anything.

LORAM = 1, HIRAM = 1, GAME = 1, EXROM = 0
This is the cart startup memory configuration.
BASIC is in for error messages.
E000-FFFF Kernal
D000-DFFF IO/CHR
C000-CFFF RAM
A000-BFFF BASIC
8000-9FFF ROML
4000-7FFF RAM
1000-3FFF RAM
0000-0FFF RAM

LORAM = 1, HIRAM = 1, GAME = 0, EXROM = 0
GAME is toggled and we loose BASIC and we get ROMH.
Copy rom to basic memory then switch to the next memory configuration.
E000-FFFF Kernal
D000-DFFF IO/CHR
C000-CFFF RAM
A000-BFFF ROMH
8000-9FFF ROML
4000-7FFF RAM
1000-3FFF RAM
0000-0FFF RAM

After loading Durexforth from ROM we should switch to:
LORAM = 0, HIRAM = 1, GAME = 1, EXROM = X (dont care)
or
LORAM = 0, HIRAM = 0, GAME = X, EXROM = 0
No cart ROM, Durexforth standard memory.

E000-FFFF Kernal
D000-DFFF IO/CHR
C000-CFFF RAM
A000-BFFF RAM
8000-9FFF RAM
4000-7FFF RAM
1000-3FFF RAM
0000-0FFF RAM

And, Kernal out for bitmap reads.
LORAM = 1, HIRAM = 0, GAME = 1, EXROM = X

E000-FFFF RAM
D000-DFFF IO/CHR
C000-CFFF RAM
A000-BFFF RAM
8000-9FFF RAM
4000-7FFF RAM
1000-3FFF RAM
0000-0FFF RAM

**Comment by bvl1999** [comment]
Thanks for picking up the merge request!

**Comment by bvl1999** [comment]
> 
> 
> #376 It seems that it's toggling ROM at $a000 in and out by toggling GAME, while EXROM remains pulled to 0 by the cart. And then there's LORAM and HIRAM in address $01.

<snip>

Yes that is correct. Writing to $de00 enables the top 8k of a Simons basic crt, and reading $de00 disables it, which the rom to ram copy code does when it is done, and before calling the startup code of durexforth. 

While I was looking into this, I was wondering if the low 8k of the crt wouldn't be an issue, but as your overview shows, and similar to what I found, it isn't. 

There is a slightly different way to solve this, there exist subtypes of the sbasic crt (westerman, blackbox) which at first glance would seem like a better fit, as they always start in 16k mode, and a read from $de00 can disable their rom completely (both game and exrom going inactive). But I'm not confident those subtypes are supported well by everything which uses .crt files... and as your overview shows, it isn't needed anyway.

**Comment by jkotlinski** [comment]
It sounds like a good thing to be able to switch out the cartridge
entirely. Does that mean either RAM or BASIC would be acccessible in
a000-bfff range? It can be sometimes useful to reuse BASIC code and data.

**Comment by bvl1999** [comment]
> 
> It sounds like a good thing to be able to switch out the cartridge entirely. Does that mean either RAM or BASIC would be acccessible in a000-bfff range? It can be sometimes useful to reuse BASIC code and data.

If this would help the project, I can put a bit of time into researching this over the weekend.
- check which subtype or alternative .crt type would allow completely disabling till reset (memory says there is a variation which can be turned on again on request, and one which will be permanently off till reset.. but.. details are a bit hazy)
- check for changes needed to the rom to ram copy and startup code. Specifically, the code which disables cartridge rom should be running from ram. Right now, that is kinda the case, as the top 8k cartridge rom gets disabled by code running from the low 8k cartridge rom, which in turn gets disabled later by code running from ram. The easy solution for that would be to simply prepend the 'disable cartridge' code before the startup code at $080d... ie, have a lda $de00 at $080a or such.

Anyway, let me know if you'd be interested in that. Its not really a lot of work when you are familiar with this stuff, and I really really like this project, so would be happy to help out with this.

**Comment by jkotlinski** [comment]
Hi! It is perhaps not important, but certainly nice, if the cartridge
version has this possibility to access BASIC. If you have time to spare and
it amuses you, I would welcome a PR! Especially if it can be done in a
manner that is well supported by various hardware and emulators.

**Comment by bvl1999** [comment]
> 
> Hi! It is perhaps not important, but certainly nice, if the cartridge version has this possibility to access BASIC. If you have time to spare and it amuses you, I would welcome a PR! Especially if it can be done in a manner that is well supported by various hardware and emulators.

Ok, will put some time in that this weekend, and make a PR.

And agree, compatibility with emulators and various hardware is important indeed. I'll check against vice, U64 and UII+, Robin Herbron promised to help testing against kung fu flash, should still find people who have a backbit and ezflash, tho those should behave the same as kung fu flash for this... but should and do are not always one :-)

**Comment by bvl1999** [comment]
So after doing a bit of research, I have some findings to share.

One important consideration imo is common uses for io range: de00-dfff

Almost every freezer cartridge and cartridge with some kind of banking support
uses at least $de00-deff, and often also $df00-dfff, and any cartridge we can disable
will need this as well.

This area also has uses for expansion hardware like the 17xx REU, Swiftlink 
modems and emulation of those, interfacing with hardware like the U64 or UII+, talking to vice etc. Almost all
of those either require the $df00-dfff range, or can be configured to use that range.

So ideally, Duraforth should use a cartridge type which only uses $de00-deff
range and leaves $df00-dfff free for use, so it can coexist with such devices, and people could create drivers for
those if they want to.

Looking through the existing cartridge types, there would be 2 obvious candidates 
which let you turn them off completely and provide a simple 16k block of rom:
- westermann
- blackbox v3
But it turns out both want to use $df00-dfff also, and that would get in the way 
of using the mentioned expansion hardware.

There is another cartridge type which can be turned off completely, but requires
somewhat more fancy cartridge code. I will have to play a bit with that one
to see how involved that would be. It looks way too fancy for what is needed,
but I'm not sure yet how much that really complicates things. 

So question to the maintainers of Durexforth: as discussed, being able to access
basic rom would be a nice to have. Is this also true for at least in theory
being able to support devices like the 17xx REU, the interface to communcate with 
the UII+/U64 hardware hardware etc? and would it be ok if that means people have
to use the disk version if they want that?

If so, and using $df00-$dfff isn't a problem, this is a trivial change.
If df00 should remain free for use, it is going to be a bit more work, can't really
say how much yet.

My own hunch is that being able to support such expansion hardware at least in theory
should be more than just a nice to have, also for the cartridge based version.

Ah yes, while vice is rather quirky in what combinations it allows, combining
a REU with cartridges which don't use the df00 area, with help of a port expander
works fine, and devices like the U64 and UII+ can also do this internally (so emulate
both an REU and a cartridge based on a crt file, and if you want, a swiftlink modem etc)

So it is a choice between.. complications when wanting to use basic rom in the cartridge version, having a simple to understand crt type which can't coexist with the REU and such, or a more complex crt type with more complex cartridge code. 

I think its not my call to make a choice in that.

**Comment by Whammo** [comment]
I have used the combination of Aprospand, REU, Swiftlink and WarpSpeed cart on a real machine. I am at a loss how this is possible.

**Comment by bvl1999** [comment]
> I have used the combination of Aprospand, REU, Swiftlink and WarpSpeed cart on a real machine. I am at a loss how this is possible.

Iirc, warpspeed only needs the de00-deff range, so reu would work. swiftlink can usually be configured to not be in the de00 range, so.. that should also work. I use a modern x-pander 3 for when I want to combine my SID Symphony cart with an REU and a 'real' rom cartridge.

But usually I use an UII+ to emulate both swiftlink and reu, and that can coexist with for example the simons basic crt type, and so those could be accessed with a theoretical durexforth driver. 

Cartridges like Action Replay, Power Cartridge, Final Cartridge, those tend to rather get in the way of everything, Super Snapshot is a bit friendlier and can coexist with things that need $df00, same for the Retro Replay, and from what I recall, Warpspeed (and also warpspeed128)

All of those have interesting functionality, support multiple rom banks, some even have a bit of extra ram. Those would be really interesting for creating a cartridge version which can run from cartridge rom directly, while being able to use around 60k of ram, but that would seem like a much larger undertaking. 

So.. either sticking with the simons basic crt, or switching to the somewhat more fancy business basic crt type would allow access to an REU and other hardware in the $df00 io range. Using the easier to use westermann or blackbox 3 types would not.

**Comment by bvl1999** [comment]
As a random aside, until a few days ago, I had never heard about this project.. and I have only very little background with forth.. You guys did a really good job at making it easy to build this, get it up and running, and get some hands-on feeling for what it can do. Source is also rather easy to navigate.

**Comment by Whammo** [comment]
It has been said that Durexforth is a labor of love. With that I would have to agree. :-)
 If at some point the 128 port were realized, I think the ideal would be a WarpSpeed type cart, complete with 64/128 switch.

**Comment by jkotlinski** [comment]
Wow, what a thorough investigation!
I think it is more important to support various accessories than to support
BASIC access.

**Comment by jkotlinski** [comment]
A practical good thing with Simons’ Basic is that its very widespread and
well supported.

For Business Basic, I can’t find it on eBay and the cartconv utility does
not support it. So its seems like a somewhat less practical option.

**Comment by bvl1999** [comment]
@jkotlinski  wrote:

> 
> A practical good thing with Simons’ Basic is that its very widespread and well supported. For Business Basic, I can’t find it on eBay and the cartconv utility does not support it. So its seems like a somewhat less practical option.

They are supported by vice, but it adds a fair bit of cartridge code, because it tries to replace kernal, not unsolvable, but seems like rather needless complications.

Simons Basic is simple and supported by about everything, and with that small 3 byte patch you merged, should not be sensitive to slight implementation differences between emulators etc.

So, I think it is the best option, at least for the current setup (copy everything to ram, and run it from there). 

@Whammo wrote:

> "I think the ideal would be a WarpSpeed type cart, complete with 64/128 switch."

I don't think there is a need for using the warpspeed128 hardware really. 128 mode is much more flexible and nice when it comes to expansion roms. You can simply ask mmu to enable/disable the bottom and top 16k of a rom, without all the hassle and inter-dependency between system and expansion rom you get on a 64. So a 128 cartridge version could, and imo should be done as a regular c128 function rom. When doing that right, people could take the image, put it on an eprom, and stick it into the internal U36 rom socket, and have their machine startup with durexforth instead of basic if they so desire.

Warpspeed128 hardware is somewhat simpler compared to warpspeed64, for the reason above, it does not need any bankswitching hardware, the mmu is used for that. But it does need to mirror part of its cartridge rom to $de00, similar to what your typical utility and fastload cartridge on the 64 also does. For warpspeed128 and 64 alike, that provides a tiny bit of space for code to which the load/save etc vectors are pointed, and which will be available in every memory configuration in which those vectors could be used, and in which the 'normal' cartridge rom should not be visible.  (bank 15 for the c128, any config in which kernal and io exist on a 64)

That can be interesting when you want to create something which seemlessly integrates with BASIC, but.. for real cartridge hardware, its no longer a straightforward cartridge.

**Comment by Whammo** [comment]
Warpspeed is the only speeder I use and the menu system is top-notch. I'm 90% to a similar launcher for Durexforth.
  Thanks for sorting out the cart and leading me to a better understanding of the expansion port.

**Comment by bvl1999** [comment]
> 
> 
> Warpspeed is the only speeder I use and the menu system is top-notch. I'm 90% to a similar launcher for Durexforth. Thanks for sorting out the cart and leading me to a better understanding of the expansion port.

My pleasure. I have a better understanding of some of the more exotic crt files now, so looks like we all gained something from this. 

A nice thing about warpspeed128 is it only needing 16k, whereas a function rom can be 32k. It would need a very small change to the cartridge hardware and code, but it seems viable to have a fully functioning warpspeed128 with DurexForth added to it (in the top 16k). This also works with the emulators which support warpspeed128. The one issue of course is neither warpspeed64 or warpspeed128 being widely supported by emulators and modern hardware. Iirc vice supports warpspeed64 (at least it seems to have code for this), and the Ultimate II and II+ support warpspeed128, but nothing else does. 

I'm working on integrating various c128 function roms, including servant128 and ws128, with https://www.bartsplace.net/content/publications/devicemanager128.shtml so it can start any of those after activating itself. It can use upto 1mb rom space, so plenty room for such things, and for adding a bunch of programs which run from ram, but can be loaded from rom similar to what DurexForth currently does. A while ago I wrote https://github.com/bvl1999/fromify which essentially lets you turn a c128 mode .prg file into a c128 function rom/cartridge. That is functionally equivalent to the cartridge startup code DurexForth uses, but for 128 mode.

Servant128 already works in the dev version, ws128 might make it into the next release, through it has some complications, so probably has to wait for an update next year. But keep in mind, all that is Ultimate II and II+ specific. It might get support in backbit at some point, and also in vice possibly (the extension to the crt format to make this possible was coordinated with vice, and cartconv from the dev tree will recognize them, but won't create them)

**Comment by jkotlinski** [comment]
Is there any outstanding work connected to this issue, or fine to close?

**Comment by renekint** [comment]
I don't know yet - have you adapted durexforth to accommodate the feature?
(and a release?)
Then I can test it.

Regards,
René


Op wo 29 dec. 2021 om 10:25 schreef Johan Kotlinski <
***@***.***>:

**Comment by bvl1999** [comment]
From my point of view, no. The fix for the original issue was merged, and seems to be fine. Investigating a possible alternative cartridge showed for now the choice is fine, so no change there for as far as I can see.

So from my point of view this can be closed.

**Comment by jkotlinski** [comment]
I close the issue then.
