### ISSUE TITLE
How to escape edit mode in Vim on VICE

### ISSUE THREAD

**Issue by hunar1997** [jkotlinski/durexforth#573]
Hello

Sorry to ask this here, I use VICE and whenever I get into edit mode, I cant get out. I'm an experienced vim user but pressing Esc on VICE doesn't do anything, along with every other button on my keyboard. Is there a way to remap the VICE button that DurexForth's vim needs to exit edit mode?

**Comment by jkotlinski** [comment]
Hi!
Since C64 lacks ”Escape”, that functionality is mapped to the ”<-” key.
The ”<-” key does not exist on PC keyboards. Typically it is mapped to the
key to the left of ”1”.
If it is not the case for you, you could try switching from Symbolic to
Positional keymap.
You can read all about it in Vice docs:
https://vice-emu.sourceforge.io/vice_1.html

lör 13 juli 2024 kl. 14:58 skrev hunar ***@***.***>:

**Comment by hunar1997** [comment]
Thank you :D changing to positional did the trick
